"""add limits in varchars fields to 100

Revision ID: 122e910f791f
Revises: 98587f60fa03
Create Date: 2025-08-31 18:25:53.445157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122e910f791f'
down_revision: Union[str, Sequence[str], None] = '98587f60fa03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'books', ['title'])
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
